In [4]:
# Package imports
import numpy as np
import matplotlib.pyplot as plt
from testCases_v2 import *
import sklearn
import sklearn.datasets
import sklearn.linear_model
from planar_utils import plot_decision_boundary, sigmoid, load_planar_dataset, load_extra_datasets

%matplotlib inline

np.random.seed(1) # set a seed so that the results are consistent

In [5]:
X, Y = load_planar_dataset()

# components

Initiate W and B

forward propagation : Z and A

backwared propagation : derivatives of J with respect to W,B,Z

propagate : combines fw and bw propagation



In [6]:
print('number of features :', X.shape[0] )
print('number of examples :', X.shape[1] )

number of features : 2
number of examples : 400


In [7]:
def sigmoid(x):
    return 1/(1+ np.exp(-x))

In [8]:
def Init_(X,Y,n_h = 4):
    '''
    returns
    n_x : size of input layer
    n_h : size of hidden layer
    n_y : size of output layer
    '''
    n_x = X.shape[0] # number of features
    n_y = Y.shape[0] # output shape
    return n_x,n_y,n_h

In [12]:
def initiation(X,Y,n_h = 4):
    n_x,n_y,n_h = Init_(X,Y,n_h = n_h)
    w1 = np.random.randn(n_h,n_x) * .1
    w2 = np.random.randn(n_y,n_h) * .1
    b1 = np.zeros((n_h,1))
    b2 = np.zeros((n_y,1))
    
    parameters = {
        'w1': w1,
        'w2': w2,
        'b1': b1,
        'b2': b2,
    }
    return parameters

In [13]:
def FW_prop(X,Y,w1,b1,w2,b2):
    
    Z1 = np.dot(w1, X) + b1
    A1 = sigmoid(Z1)
    Z2 = np.dot(w2, A1) + b2
    A2 = sigmoid(Z2)
    parameters = {
        'A1' : A1,
        'Z1' : Z1,
        'A2' : A2,
        'Z2' : Z2
    }
    return parameters

In [14]:
w1 = initiation(X,Y,n_h = 4)['w1']
b1 = initiation(X,Y,n_h = 4)['b1']

w2 = initiation(X,Y,n_h = 4)['w2']
b2 = initiation(X,Y,n_h = 4)['b2']
a1,a2,z1,z2 = FW_prop(X,Y,w1,b1,w2,b2)

$W^{[1]}_1$ :
```

array([[ 0.08143431,  0.07804699],
       [-0.14640536, -0.01544912],
       [-0.00924323, -0.02378753],
       [-0.07556628,  0.18514379]])
```
$B^{[1]}_1$ :
```

array([[0.],
       [0.],
       [0.],
       [0.]])

```
sample from X :
```
array([[ 1.20444229,  3.57611415],
       [ 0.1587099 , -1.4821709 ],
       [ 0.0952472 , -1.27995533],
       [ 0.34917847, -2.06437997],
       [ 0.69415038,  2.88910878]])
```
Computations for Node 1 of the first layer :

$$
\text{In this case} A^{[0]} := X \\
\text{so}  \\
z^{[1]}_1 = w^{[1]T}_1 * x + b^{[1]}_1 := 1.20444*0.08143 + 3.5761*0.07804  + 0 \\ 
A^{[1]}_1 = activation ( z^{[1]}_1 )
$$

# General Formula :

$$
Z^{[i]} = W^{[i]} * A^{[i-1]} + B^{[i]}  \\
A^{[i]} = activation (Z^{[i]}) \\
$$

In [15]:
def BW_prop():
    pass

In [58]:
1.20444229*0 + 3.57611415*0  + 0 = w.T * x + b first node 
sigmoid (1.20444229*0 + 3.57611415*0  + 0 ) = A first node

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])